const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_13_48_08_02_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNzIsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMzQsXG4gICAgICAgIDM4LFxuICAgICAgICA3NCxcbiAgICAgICAgMTIsXG4gICAgICAgIDE4NixcbiAgICAgICAgNjMsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTc5LFxuICAgICAgICAxNDcsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMixcbiAgICAgICAgMjI2LFxuICAgICAgICAxOTgsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTYyLFxuICAgICAgICA5MCxcbiAgICAgICAgMjAxLFxuICAgICAgICAyNDEsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMjAyLFxuICAgICAgICA3NSxcbiAgICAgICAgMTExLFxuICAgICAgICAyMzksXG4gICAgICAgIDIyNixcbiAgICAgICAgMTgxLFxuICAgICAgICAzLFxuICAgICAgICAxNDEsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMjQzLFxuICAgICAgICA4NlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNjksXG4gICAgICAgIDEzMSxcbiAgICAgICAgMjA3LFxuICAgICAgICAyMjksXG4gICAgICAgIDIyNSxcbiAgICAgICAgMTU1LFxuICAgICAgICAyMzksXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjMzLFxuICAgICAgICAyNyxcbiAgICAgICAgMTY5LFxuICAgICAgICAzMyxcbiAgICAgICAgMTE3LFxuICAgICAgICAyMzUsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTE2LFxuICAgICAgICAyMzQsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMjE1LFxuICAgICAgICAxNDQsXG4gICAgICAgIDQ3LFxuICAgICAgICAyMDIsXG4gICAgICAgIDc0LFxuICAgICAgICA0NixcbiAgICAgICAgMTc5LFxuICAgICAgICAxNjksXG4gICAgICAgIDI1NSxcbiAgICAgICAgMjUwLFxuICAgICAgICAxOTIsXG4gICAgICAgIDE5MSxcbiAgICAgICAgOTAsXG4gICAgICAgIDUxXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4OCxcbiAgICAgICAgMTAzLFxuICAgICAgICAxOSxcbiAgICAgICAgNSxcbiAgICAgICAgMzksXG4gICAgICAgIDc3LFxuICAgICAgICAxMjAsXG4gICAgICAgIDE2MSxcbiAgICAgICAgNTYsXG4gICAgICAgIDE3LFxuICAgICAgICAxMzQsXG4gICAgICAgIDcyLFxuICAgICAgICAyMzQsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTYsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMzAsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMjIsXG4gICAgICAgIDY0LFxuICAgICAgICA4NSxcbiAgICAgICAgMTMsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjI5LFxuICAgICAgICAxOCxcbiAgICAgICAgMjI2LFxuICAgICAgICAxOTksXG4gICAgICAgIDMxLFxuICAgICAgICAxNTUsXG4gICAgICAgIDIxNixcbiAgICAgICAgMTUxLFxuICAgICAgICAxMDBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODUsXG4gICAgICAgIDI1LFxuICAgICAgICAxODcsXG4gICAgICAgIDI0MSxcbiAgICAgICAgNTMsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMjQ4LFxuICAgICAgICA4OCxcbiAgICAgICAgMTEyLFxuICAgICAgICA4MyxcbiAgICAgICAgMTAwLFxuICAgICAgICAxMixcbiAgICAgICAgNjYsXG4gICAgICAgIDE5LFxuICAgICAgICAyMTYsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjA2LFxuICAgICAgICA1MixcbiAgICAgICAgMTE1LFxuICAgICAgICAyMDcsXG4gICAgICAgIDg0LFxuICAgICAgICA5MyxcbiAgICAgICAgMTE4LFxuICAgICAgICAxNjgsXG4gICAgICAgIDEwNyxcbiAgICAgICAgODcsXG4gICAgICAgIDUzLFxuICAgICAgICAxNTIsXG4gICAgICAgIDIxMSxcbiAgICAgICAgNjQsXG4gICAgICAgIDk0LFxuICAgICAgICAyN1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzIsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMTE3LFxuICAgICAgICAxMjMsXG4gICAgICAgIDQxLFxuICAgICAgICAxMzEsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMjMwLFxuICAgICAgICAyMDUsXG4gICAgICAgIDIzLFxuICAgICAgICAxOSxcbiAgICAgICAgMjQ4LFxuICAgICAgICA4MyxcbiAgICAgICAgMTc5LFxuICAgICAgICAxODYsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTc3LFxuICAgICAgICAxNyxcbiAgICAgICAgMTY5LFxuICAgICAgICAxODIsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMjM3LFxuICAgICAgICA0OSxcbiAgICAgICAgMzEsXG4gICAgICAgIDExMyxcbiAgICAgICAgNzIsXG4gICAgICAgIDIzOCxcbiAgICAgICAgNjgsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMjQ5LFxuICAgICAgICA5MSxcbiAgICAgICAgMTA1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE4OSxcbiAgICAgICAgMjE3LFxuICAgICAgICAyMjIsXG4gICAgICAgIDIwOCxcbiAgICAgICAgNjUsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTM0LFxuICAgICAgICA2OCxcbiAgICAgICAgOTMsXG4gICAgICAgIDQxLFxuICAgICAgICA2NSxcbiAgICAgICAgOTcsXG4gICAgICAgIDEzMixcbiAgICAgICAgMjU0LFxuICAgICAgICAyMDAsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMjI5LFxuICAgICAgICAxNzUsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTU2LFxuICAgICAgICA3OCxcbiAgICAgICAgMTk1LFxuICAgICAgICAxMDksXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTExLFxuICAgICAgICAxMDgsXG4gICAgICAgIDY4LFxuICAgICAgICA1NSxcbiAgICAgICAgNTcsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMjIzLFxuICAgICAgICA2NVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgNDIsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgMTY4LFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMjIzLFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDgyLFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTY0LFxuICAgICAgICAgIDIzMSxcbiAgICAgICAgICAxMjEsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDgxLFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICA5MlxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMzEsXG4gICAgICAgICAgNjksXG4gICAgICAgICAgMSxcbiAgICAgICAgICA5MSxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAzNyxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICA1LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICA5NixcbiAgICAgICAgICAxODksXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDIwMyxcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAxMTMsXG4gICAgICAgICAgMTQxLFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICA2NSxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgNjksXG4gICAgICAgICAgMzhcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMzEsXG4gICAgICAgIDgyLFxuICAgICAgICAyMTYsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTQ4LFxuICAgICAgICAyNixcbiAgICAgICAgMTAyLFxuICAgICAgICAxMjAsXG4gICAgICAgIDIzNCxcbiAgICAgICAgNzQsXG4gICAgICAgIDE3LFxuICAgICAgICAxNjEsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTUyLFxuICAgICAgICAxMDksXG4gICAgICAgIDk2LFxuICAgICAgICAyNCxcbiAgICAgICAgOTEsXG4gICAgICAgIDc2LFxuICAgICAgICAyMTcsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTg4LFxuICAgICAgICAyMjMsXG4gICAgICAgIDU0LFxuICAgICAgICAxOTUsXG4gICAgICAgIDYsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTk2LFxuICAgICAgICAxMjEsXG4gICAgICAgIDIwLFxuICAgICAgICAyMDgsXG4gICAgICAgIDk5LFxuICAgICAgICA2MyxcbiAgICAgICAgMjM2LFxuICAgICAgICAyNTUsXG4gICAgICAgIDIyMSxcbiAgICAgICAgOSxcbiAgICAgICAgMzAsXG4gICAgICAgIDY2LFxuICAgICAgICAxMTQsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTA2LFxuICAgICAgICAzMixcbiAgICAgICAgMTYyLFxuICAgICAgICAzNyxcbiAgICAgICAgMTk2LFxuICAgICAgICA4OSxcbiAgICAgICAgNDAsXG4gICAgICAgIDcsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTYwLFxuICAgICAgICAxNjYsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMTEwLFxuICAgICAgICAxNyxcbiAgICAgICAgMTQ1LFxuICAgICAgICA0NixcbiAgICAgICAgMjExLFxuICAgICAgICAyNDMsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjUzLFxuICAgICAgICAyMTMsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTMzXG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxOTEsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwibVVySmY3UXp0ZVUwVy92T29CMklFSTVrU3Npa2FKU01HTlV0d3RmSnlOVT1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ3MDQ4MDI2NjA2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJBNjU0QkY4REU2MjM0ODE2ODhBODJERTU5MUMxOTQ3RFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjI2MDY1MTNcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwib3A5ams2Q3hTZk9tYUZkSkNRZXBNd1wiLFxuICBcInBob25lSWRcIjogXCJjOTk0NmVhOS1lOGNlLTRiNTQtODcyMy1jYjdhYWQyODBkMjhcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNTAsXG4gICAgICAxMzAsXG4gICAgICAxMzUsXG4gICAgICA5OSxcbiAgICAgIDkwLFxuICAgICAgMjAwLFxuICAgICAgMTM2LFxuICAgICAgNyxcbiAgICAgIDE2NixcbiAgICAgIDIwNixcbiAgICAgIDQ3LFxuICAgICAgMjM5LFxuICAgICAgMTI2LFxuICAgICAgMTY2LFxuICAgICAgMjIyLFxuICAgICAgMjM0LFxuICAgICAgMjI2LFxuICAgICAgMTM4LFxuICAgICAgMjEzLFxuICAgICAgMjdcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDIwLFxuICAgICAgMjE3LFxuICAgICAgMTAwLFxuICAgICAgMjUyLFxuICAgICAgMjM3LFxuICAgICAgMjEyLFxuICAgICAgMTMxLFxuICAgICAgMTcyLFxuICAgICAgMTMsXG4gICAgICA2NyxcbiAgICAgIDIxMSxcbiAgICAgIDEwOCxcbiAgICAgIDE3MSxcbiAgICAgIDE2NyxcbiAgICAgIDcxLFxuICAgICAgMjI2LFxuICAgICAgMTg5LFxuICAgICAgNzAsXG4gICAgICAzMyxcbiAgICAgIDEyOFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0srbnB2QUNFS3JIczdVR0dBTWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiQUZwZkRUeUE2eVlILzBMMDB2NmFMcDB1aTNETVYzVWdmYWx6YzZVOHFVaz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJaUTY5eFJ4Wmc1YXJuNmNrbVk5Zmg3OGRYdUN5a0VzNVMyOWk1WlJNQUZCakpKU012REFzZDFvNnBJK2V2M3dVc2trY2h2ci9pOTNDNlJzRHJDcGRBUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJGL3k1cjFDKzhkL04xakZnVm9vWnA3QklwdVZMeHlXS0JoZXV3c1cwaVFnY1ovKzRzSFBpVW54K1lGRU5YM0JObytCaWc2U3JoYXUxWHVIR0hRVXloQT09XCJcbiAgfSxcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDcwNDgwMjY2MDY6OEBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIlTDpWxsw6lzdFwiLFxuICAgIFwibGlkXCI6IFwiMjI5NTIzMTE5NDUyMTkzOjhAbGlkXCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ3MDQ4MDI2NjA2OjhAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAwLFxuICAgICAgICAgIDkwLFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgMzgsXG4gICAgICAgICAgNyxcbiAgICAgICAgICAyNTUsXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDIxMCxcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICA0NixcbiAgICAgICAgICAxMzksXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICA4NyxcbiAgICAgICAgICAxMTcsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAxNjksXG4gICAgICAgICAgNzNcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcInNtYmFcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyMjYwNjUxMCxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQURsQlwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRGsrLmpzb24iOiAie1wia2V5RGF0YVwiOlwicEc4US90QUsrL0VkQTAvWjM3TmhQVHlLSFZoWThMRGgzcnU1dGtkRUNQOD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjo3NzIzNzk1NjQsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjIwODMzNjY3ODlcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFEazkuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCI2a2loRW5jU292cDhTcFUxSHMyWnVNUWRCbzRqM0ZrK3VnOENrRS8vNFBrPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjc3MjM3OTU2NCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRGtfXy5qc29uIjogIntcImtleURhdGFcIjpcIjhWZmwrd0Mxb1hpUC90MHBnTjV3UU8xUXNsTDFLMFVDZnR2bHE5NmxLVEk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6NzcyMzc5NTY1LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFEbEEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJYcHc4SzY3bTdNem5EWkNpU21Bd0gva0MrSVFOM0FqWWhMOVhKUkg3cElVPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjc3MjM3OTU2NSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcyMjA4NTQ4NDg3NlwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQURsQi5qc29uIjogIntcImtleURhdGFcIjpcInA1dng0SWVYMUhJNER4MUVwaG5zSFZDbEhDRURIQThtc1FlRS9sVDdITUk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6NzcyMzc5NTY2LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFEbEMuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCIreUVXVFQ0MDFlV1V4VHZEelRSQkNKMUk5MHhqaFZzUWF0T3loKzJPVExnPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjc3MjM3OTU2NixcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcyMjMzNTE1NzIwN1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQURsRC5qc29uIjogIntcImtleURhdGFcIjpcImYrYjZSRjJUa1VSSXJ5UVplZEJoY2hZdGthVkFqSWFhTmhNcWxESFFBb0E9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6NzcyMzc5NTY3LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFEbEUuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJqTjV2VmN2eHpVZExsd0NkQzB2bFM5K1Q0SGYxTm9pTk5saUlqUTdQUnpFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjc3MjM3OTU2NyxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMl19LFwidGltZXN0YW1wXCI6XCIxNzIyNjA0OTkwNjA2XCJ9Igp9"  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
